---
- name: install webupd8 apt key
  apt_key: id=EEA14886 keyserver='keyserver.ubuntu.com' state=present

- name: install webupd8 team java ppa (for oracle java)
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present
  when: java_needs_oracle

- name: remove webupd8 team java ppa (for oracle java)
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=absent
  when: java_cleanup and not java_needs_oracle
