---
- name: install dependencies using apt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items: requirements

- name: install elasticsearch signing key for apt
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: install elasticsearch repository for apt
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/0.90/debian stable main' state=present

- name: install elasticsearch and dependencies using apt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items: debian_packages

