---
galaxy_info:
  author: playlist
  company: Playlist
  description: Installs OpenJDK / Oracle JDK 6, 7, 8
  min_ansible_version: 1.8
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
        - All
  categories:
    - system

dependencies: []
