---
# tasks file for otw-perlbrew
# tasks file for otw-rvm
- name: Update bashrc for rvm for vagrant user
  lineinfile:
    dest=/home/{{otw_perlbrew_user}}/.bashrc
    line="[[ -s $HOME/.perlbrew/etc/bashrc ]] && . $HOME/.perlbrew/etc/bashrc" 
    regexp="^\[\[ -s \\$HOME/\.perlbrew/etc/bashrc"
    owner=vagrant
    state=present
    insertafter=EOF
    create=True
- name: Make directories
  file: dest=/home/vagrant/{{item}}  mode=755 owner=vagrant group=vagrant state=directory
  with_items:
    - bin
- name: copy bin files
  copy: src={{item}} dest=/home/vagrant/bin/ mode=0755 owner=vagrant group=vagrant 
  with_items:
    - reset_perl
- name: Run install scripts
  shell: /home/vagrant/bin/bin/reset_perl
  become: yes
  become_user: vagrant
